# Generated by Django 3.0.4 on 2020-03-12 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='image',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='film',
            name='release_date',
            field=models.DateField(),
        ),
    ]
